version: 2.0.{build}
branches:
  only:
  - master
  - development

#skip_commits:
# files:
#   - dir/*
# Build worker image (VM template)
image: Visual Studio 2017

clone_folder: C:\netsel1

environment:
  COVERALLS_REPO_TOKEN:
    secure: h6mvV5hoQ4GdIDvrY2fUEoNFFg94glGed

install:
- choco install googlechrome

before_build:
  - dotnet restore .\src\Levi9.NetSel.sln
  - dotnet restore .\src\Levi9.NetSel.UI.Tests\Levi9.NetSel.UI.Tests.csproj
  - dotnet restore .\src\Levi9.NetSel.Unit.Tests\Levi9.NetSel.Unit.Tests.csproj
  - nuget restore .\src\Levi9.NetSel.sln
  
build:         
  project: .\src\Levi9.NetSel.sln
  
#after_test:
#- ps: >-
#    mkdir coverage-results

#    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:..\..\xunit.runner.console.2.1.0\tools\xunit.console.exe "-targetargs:..\..\..\Levi9.NetSel.Test\bin\Debug\Levi9.NetSel.Test.dll -noshadow" "-filter:+[Levi9.NetSel*]* -[*Tests]*" -skipautoprops -output:..\..\..\coverage-results\results.xml

#    .\packages\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover --input .\coverage-results\results.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
  
after_build:
 - cmd: >-
    nuget pack .\src\Levi9.NetSel\Levi9.NetSel.csproj -Version %appveyor_build_version%
    
artifacts:
- path: .\Levi9.NetSel.2.*.nupkg
  name: Levi9.NetSel
  
deploy:
  provider: NuGet
  api_key:
    secure: mFy9s4WsrHTm3aBLlMeBEW7pesMNVwRsvseKMYpfwUdJdWmkNfnHePWOM8oLHB8G
  artifact: /.*\.nupkg/

notifications:
- provider: Email
  to:
  - sukamilan@gmail.com
  - mvajs1@gmail.com
  subject: Levi9.NetSel deployment
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
